#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="$ROOT_DIR/infra/terraform"
FLOCI_ENV_FILE="$TF_DIR/.env.floci"
COMPOSE_FILE="$ROOT_DIR/docker-compose.yml"

# CREATE_RDS: set to "true" (via `make dev-iac`) to provision RDS via Floci
# for Terraform/IaC validation. This overrides DB_HOST/DB_PORT in .env.floci
# to point at the Floci-emulated RDS endpoint, which doesn't support TLS at
# all — so `make dev-iac` does not start the app (see README "Validating the
# RDS Terraform module").
#
# CREATE_MSK: kept for completeness but always false in practice — a Floci
# bug (the MSK cluster never leaves state CREATING) hangs `terraform apply`
# indefinitely. Do not set this until that's fixed upstream.
TF_OVERRIDES=(
	"-var=create_rds=${CREATE_RDS:-false}"
	"-var=create_msk=${CREATE_MSK:-false}"
)

# ── Docker Desktop ────────────────────────────────────────────────────────────
if ! docker info >/dev/null 2>&1; then
	echo "==> Starting Docker Desktop..."
	open -a Docker
	printf "    Waiting for Docker"
	until docker info >/dev/null 2>&1; do
		printf "."
		sleep 2
	done
	echo " ready"
fi

# ── Docker Compose (everything except postgres — it needs Vault PKI certs
# generated below before it can start) ─────────────────────────────────────
echo "==> Starting Docker Compose services..."
NON_POSTGRES_SERVICES=$(docker compose -f "$COMPOSE_FILE" config --services | grep -v '^postgres$')
# shellcheck disable=SC2086
docker compose -f "$COMPOSE_FILE" up -d $NON_POSTGRES_SERVICES

# ── Floci health ──────────────────────────────────────────────────────────────
printf "==> Waiting for Floci"
until curl -sf http://localhost:4566/_floci/health >/dev/null 2>&1; do
	printf "."
	sleep 2
done
echo " ready"

# ── Vault health ─────────────────────────────────────────────────────────────
printf "==> Waiting for Vault"
until curl -sf "http://localhost:8200/v1/sys/health?standbyok=true" >/dev/null 2>&1; do
	printf "."
	sleep 2
done
echo " ready"

# ── Terraform init (always — idempotent and fast when nothing has changed) ────
echo "==> Running terraform init..."
terraform -chdir="$TF_DIR" init -upgrade

# ── Terraform apply — credentials injected from .env via TF_VAR_* ────────────
# shellcheck source=../.env
source "$ROOT_DIR/.env"
export TF_VAR_db_username="$DB_USER"
export TF_VAR_db_password="$DB_PASSWORD"

# ── Provision Vault PKI first — generates the two-tier CA and the Postgres
# server cert into ./.certs, which docker-compose's postgres service mounts.
# Dev-mode Vault loses its mounts on every container restart, so this re-runs
# (and re-issues certs) on every `make dev`.
echo "==> Provisioning Vault PKI (two-tier CA + certs)..."
terraform -chdir="$TF_DIR" apply \
	-target=module.vault_pki \
	-var-file=terraform.local.tfvars \
	"${TF_OVERRIDES[@]}" \
	-auto-approve \
	-compact-warnings

if [ ! -f "$ROOT_DIR/.certs/postgres-server.crt" ]; then
	echo "ERROR: $ROOT_DIR/.certs/postgres-server.crt was not generated by module.vault_pki." >&2
	echo "       Check create_vault_pki = true in terraform.local.tfvars." >&2
	exit 1
fi

# ── Start Postgres now that its TLS certs exist ──────────────────────────────
echo "==> Starting Postgres with TLS/mTLS..."
docker compose -f "$COMPOSE_FILE" up -d postgres

printf "==> Waiting for Postgres (localhost:5432)"
until nc -z localhost 5432 2>/dev/null; do
	printf "."
	sleep 2
done
echo " ready"

# ── Full apply — RDS/MSK/KMS/Vault HA per create_rds/create_msk/create_vault ──
echo "==> Provisioning remaining infrastructure..."
terraform -chdir="$TF_DIR" apply \
	-var-file=terraform.local.tfvars \
	"${TF_OVERRIDES[@]}" \
	-auto-approve \
	-compact-warnings

# ── Write dynamic outputs to .env.floci ───────────────────────────────────────
echo "==> Writing connection details to $FLOCI_ENV_FILE..."
{
	echo "# Generated by scripts/dev-up.sh — do not edit or commit"
	echo "DB_HOST=$(terraform -chdir="$TF_DIR" output -raw rds_address)"
	echo "DB_PORT=$(terraform -chdir="$TF_DIR" output -raw rds_port)"
	# Only written when MSK is provisioned (CREATE_MSK=true, e.g. `make dev-iac`)
	# Otherwise the app uses the Docker Compose Kafka at localhost:9092 (the default)
	MSK_BROKERS="$(terraform -chdir="$TF_DIR" output -raw msk_bootstrap_brokers 2>/dev/null || true)"
	if [ -n "$MSK_BROKERS" ]; then
		echo "KAFKA_BOOTSTRAP_SERVERS=$MSK_BROKERS"
	fi
	# AppRole credentials for VaultPkiClient to fetch short-lived mTLS certs
	echo "VAULT_APPROLE_ROLE_ID=$(terraform -chdir="$TF_DIR" output -raw vault_pki_approle_role_id)"
	echo "VAULT_APPROLE_SECRET_ID=$(terraform -chdir="$TF_DIR" output -raw vault_pki_approle_secret_id)"
} >"$FLOCI_ENV_FILE"

echo ""
if [ "${CREATE_RDS:-false}" = "true" ] || [ "${CREATE_MSK:-false}" = "true" ]; then
	echo "✅ Floci infrastructure provisioned for Terraform validation."
	echo ""
	echo "   RDS endpoint : $(terraform -chdir="$TF_DIR" output -raw rds_endpoint)"
	echo ""
	echo "   The app is NOT started: DB_HOST/DB_PORT in $FLOCI_ENV_FILE now point at the"
	echo "   Floci RDS endpoint above, which doesn't support TLS at all (Flyway's"
	echo "   sslmode=require would fail with 'server does not support SSL'). This is"
	echo "   expected — see the README's \"Validating the RDS Terraform module\" section."
	echo ""
	echo "   Run 'make dev' to destroy this RDS instance and return to the Docker"
	echo "   Compose Postgres + mTLS dev loop."
	echo ""
else
	echo "✅ Environment ready."
	echo "   Terminal : make dev  (or ./gradlew bootRun)"
	echo "   IDE      : run the app normally — bootRun reads .env.floci automatically"
	echo ""
fi
