#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="$ROOT_DIR/infra/terraform"
FLOCI_ENV_FILE="$TF_DIR/.env.floci"

# ── Docker Desktop ────────────────────────────────────────────────────────────
if ! docker info >/dev/null 2>&1; then
	echo "==> Starting Docker Desktop..."
	open -a Docker
	printf "    Waiting for Docker"
	until docker info >/dev/null 2>&1; do
		printf "."
		sleep 2
	done
	echo " ready"
fi

# ── Docker Compose ────────────────────────────────────────────────────────────
echo "==> Starting Docker Compose services..."
docker compose -f "$ROOT_DIR/docker-compose.yml" up -d

# ── Floci health ──────────────────────────────────────────────────────────────
printf "==> Waiting for Floci"
until curl -sf http://localhost:4566/_floci/health >/dev/null 2>&1; do
	printf "."
	sleep 2
done
echo " ready"

# ── Terraform init (always — idempotent and fast when nothing has changed) ────
echo "==> Running terraform init..."
terraform -chdir="$TF_DIR" init -upgrade

# ── Terraform apply — credentials injected from .env via TF_VAR_* ────────────
echo "==> Provisioning infrastructure..."
# shellcheck source=../.env
source "$ROOT_DIR/.env"
export TF_VAR_db_username="$DB_USER"
export TF_VAR_db_password="$DB_PASSWORD"
terraform -chdir="$TF_DIR" apply \
	-var-file=terraform.local.tfvars \
	-auto-approve \
	-compact-warnings

# ── Postgres health ───────────────────────────────────────────────────────────
RDS_HOST="$(terraform -chdir="$TF_DIR" output -raw rds_address 2>/dev/null || echo localhost)"
RDS_PORT="$(terraform -chdir="$TF_DIR" output -raw rds_port 2>/dev/null || echo 5432)"
printf "==> Waiting for Postgres (%s:%s)" "$RDS_HOST" "$RDS_PORT"
until nc -z "$RDS_HOST" "$RDS_PORT" 2>/dev/null; do
	printf "."
	sleep 2
done
echo " ready"

# ── Write dynamic outputs to .env.floci ───────────────────────────────────────
echo "==> Writing connection details to $FLOCI_ENV_FILE..."
{
	echo "# Generated by scripts/dev-up.sh — do not edit or commit"
	echo "DB_HOST=$(terraform -chdir="$TF_DIR" output -raw rds_address)"
	echo "DB_PORT=$(terraform -chdir="$TF_DIR" output -raw rds_port)"
	# Only write Kafka brokers when MSK is provisioned (create_msk = true)
	# Otherwise the app uses the Docker Compose Kafka at localhost:9092 (the default)
	MSK_BROKERS="$(terraform -chdir="$TF_DIR" output -raw msk_bootstrap_brokers 2>/dev/null || true)"
	if [ -n "$MSK_BROKERS" ]; then
		echo "KAFKA_BOOTSTRAP_SERVERS=$MSK_BROKERS"
	fi
} >"$FLOCI_ENV_FILE"

echo ""
echo "✅ Environment ready."
echo "   Terminal : make dev  (or ./gradlew bootRun)"
echo "   IDE      : run the app normally — bootRun reads .env.floci automatically"
echo ""
