CREATE TABLE ORDERS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    ITEM_NAME VARCHAR(255) NOT NULL,
    AMOUNT INT NOT NULL,
    STATUS VARCHAR(50)
);

CREATE INDEX IDX_ORDERS_STATUS ON ORDERS (STATUS);
CREATE INDEX IDX_ORDERS_ITEM_NAME ON ORDERS (ITEM_NAME);
